general:
  me: config_h2.yml
  device: [cuda:0,cuda:1,cuda:2,cuda:3]
  driver: active_learning.py
  output: [result/newdata_5k_ss_ln , 1] # root, iter
  prefix: ""

data:
  root: /global/scratch/users/nancy_guan/ML/AIMD_H_combustion/H2Combustion/local/hydrogen_data
  reaction: [1,2,3,4,8,9,10,11,12,13,14,15,16,17,18,19]
  normal_mode: True
  size_nmode_max: 4000     # will be applied to both single and multiple reaction job
  trsize_perrxn_max: 1000     # -1 for all remaining
  train_size: -1   # -1 for all remaining
  test_size: 1000
  val_size: 1000
  dialation: True
  dialation_reaction: ['01', '02', '03', '04', '05','07', '08', '09', '10', '11', '13', '14', '15', '16', '17', '18', '19']
  dialation_trsize_perrxn: 200
  cutoff: 5.0
  random_states: 90
  cgem: False

al: #active learning related settings
  added: []
  added_split: [0.8,0.1,0.1]
  metad_rxns: [9,10,13,16,17,18]
  balance_rxns: True
  disagreement_thresh: [2,99999] #the range of the maximum (over components) standard deviation on the forces to be sampled

model:
  pre_trained: False  #/global/scratch/users/nancy_guan/ML/AIMD_H_combustion/H2Combustion/local/active_learning/models_active_learning_1kperrxn_bwsl_ini/model_0/training_1/models/best_model_state.tar #False #/global/scratch/nancy_guan/ML/AIMD_H_combustion/H2Combustion/local/md/hydrogen_ln/models/best_model_state.tar
  activation: swish #ssp
  requires_dr: True
  w_energy: 1.0
  w_force: 20.0
  wf_decay: 0.0     # if 0.01: wf=1 at epoch=460
  w_f_mag: 0.0
  w_f_dir: 1.0
  resolution: 20
  n_features: 128
  n_interactions: 3
  cutoff_network: poly  # poly, cosine
  normalize_atomic: True
  shared_interactions: False
  normalize_filter: False
  return_latent: True
  layer_norm: True
  double_update_latent: True

training:
  epochs: 2000
  tr_batch_size: 100  #32
  val_batch_size: 100 #32
  tr_rotations: 0
  val_rotations: 0
  tr_frz_rot: False
  val_frz_rot: False
  tr_keep_original: True         # ##
  val_keep_original: True
  shuffle: True
  drop_last: True
  lr: 1.0e-3 #0.0005
  lr_scheduler: [plateau, 15, 20, 0.7, 1.0e-6]
#  lr_scheduler: [decay, 0.05]
  weight_decay: 0 #3.0e-5
  dropout: 0.0
  boltzmann_weights: True

hooks:
  vismolvector3d: False

checkpoint:
  log: 1
  val: 1
  test: 1
  model: 100
  verbose: False
  wandb: False




